### ISSUE TITLE
推送可以用 beartchat 或者 slack 的机器人，非常方便

### ISSUE THREAD

**Issue by MasterXuu** [425324438/huobi#1]
![img_1194a69c0ef9-1](https://user-images.githubusercontent.com/37827893/37952298-de93b518-31d1-11e8-8fa8-00a7ca5251c5.jpeg)

**Comment by YKevin0x61** [comment]
有教程吗，这个怎么配置

**Comment by MasterXuu** [comment]
可以去 beartchat 查看官方的说明和 api

**Comment by tingyuTy** [comment]
哇 厉害 厉害 蟹蟹大佬

**Comment by YKevin0x61** [comment]
今天发现了一个软件支持所有主流交易所的价格预警 (软件名：MyToken)
